Portfolio Project: mobile-first #1
Botlhale-Setou/my-first-portfolio-site pull request #1
Opened 2022-08-18 19:50 UTC by Botlhale-Setou

- Install linters
- Incorporate .gitignore
- Create/edit index.html and styles.css
- Add relevant icon images to the working directory
- Create/edit README.md
- Modify index.html and styles.css for linter compliance

2022-08-18 20:13 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @Botlhale-Setou, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 

 - No linter errors. ✔️
 - Background images match perfectly with the Figma template. ✔️

## Aspects to improve ♻️

- [x] Check the comments under the review.
- [x] Kindly group the images you use in your app in a separate folder to make the structure of your app looks cleaner.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 20:13 UTC, leonardodiasb commented on README.md
> +### Deployment
- [x] Please give some descriptive instructions for the user about how to use this app, the technologies involved, etc. Don't use unnecessary sections in your README file.

2022-08-18 20:13 UTC, leonardodiasb commented on styles.css
> +  font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
- [x] The font-family of the Figma template you followed is 'Roboto'. Kindly use the same font-family and the same font-weights from the template. This applies to all text in this project.

2022-08-18 20:13 UTC, leonardodiasb commented on index.html
> +      </div>
- [ ] The logo and the hamburger button are inside a navbar and they should be around a `<nav>` tag. Kindly group them in a proper tag for semantic reasons.
- [ ] The logo should be a link and should be inside an `<a>` tag. Kindly change that for better UX.
- [ ] The hamburger button is a button and should be inside a `<button>` tag so it can be opened in the future. Kindly change that.

2022-08-18 20:13 UTC, leonardodiasb commented on index.html
> +      </section>
- [ ] You should not use a `<section>` tag inside another `<section>` tag. You could change this for a `<div>` tag for better semantics.

2022-08-18 20:13 UTC, leonardodiasb commented on index.html
> +      </section>
- [ ] You should not use a `<section>` tag inside another `<section>` tag. You could change this for a <div> tag for better semantics.

2022-08-18 20:13 UTC, leonardodiasb commented on index.html
> +      </section>
- [ ] You should not use a `<section>` tag inside another `<section>` tag. You could change this for a <div> tag for better semantics.

2022-08-18 20:13 UTC, leonardodiasb commented on index.html
> +        </div>
- [ ] This is a list of social icons and the icons should redirect the user to your social pages. You should use `<ul>` to group the list and `<li>` tags for the items and `<a>` for the links inside the list items. Kindly change that.

2022-08-18 20:13 UTC, leonardodiasb commented on index.html
> +        </div>
- [ ] This is a button and should be a useful button written using a `<a>` tag or a `<button>` tag, not a static image. Kindly change that.

2022-08-18 20:13 UTC, leonardodiasb commented on index.html
> +          </hgroup>
- [ ] As the social list, the skill list would be better wrapped around `<ul>` tags using `<li>` tags for the items. Kindly change that. Remember the hierarchy of the heading tags, there should not be more than one `<h1>` tag in your project. Check this [link](https://www.reliablesoft.net/h1-tag/) for more info.

2022-08-19 08:40 UTC, Botlhale-Setou commented on styles.css
> +  font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
'Roboto' font installed and incorporated.

2022-08-19 10:48 UTC, Botlhale-Setou commented on index.html
> +      </div>
Changes made

2022-08-19 10:55 UTC, Botlhale-Setou commented on index.html
> +      </section>
Changed outer <section> to <div>

2022-08-19 10:56 UTC, Botlhale-Setou commented on index.html
> +      </section>
Changed outer <section to <div

2022-08-19 10:56 UTC, Botlhale-Setou commented on index.html
> +      </section>
Changed outer <section to <div

2022-08-19 15:52 UTC, Botlhale-Setou commented on index.html
> +        </div>
List of social icons converted to <ul and relevant href values substituted.

2022-08-19 15:53 UTC, Botlhale-Setou commented on index.html
> +        </div>
<img converted to <a element

2022-08-19 16:31 UTC, Botlhale-Setou commented on index.html
> +          </hgroup>
Skills lists converted to <ul elements and <h1 tags removed.

2022-08-19 18:02 UTC, Botlhale-Setou commented on README.md
> +### Deployment
README.md updated.

2022-08-19 19:17 UTC, ichala requested changes
Hi @Botlhale-Setou , 

Good job so far! 👏👏👏
There are some issues that you still need to work on to go to the next project but you're almost there!

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## To Highlight 🎉

- No Linters Errors ✔️
- Good commit messages ✔️
- PR has a good title and summary ✔️
- Readme is now professional ✔️


 ## Required Changes ♻️
 
- [ ]  _**_Check The Comments Below_**_

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  @ichala in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 19:17 UTC, ichala commented on styles.css
> +  background-image: url("top circles.png");
- [ ] good job adding all pictures inside a folder like the previous reviewer asked, kindly update the links because your background image is no longer displayed

2022-08-19 19:17 UTC, ichala commented on index.html
> +      <section class="headline-head">
- [ ] Great job updating sections and divs, for semantics reason you should wrap all of your divs inside a section and not the opposite, so kindly change the `<div class="headline">` to a section, and all childrens inside of it  to a `div`, like that you will have only one big section and divs inside of it

2022-08-19 19:17 UTC, ichala commented on index.html
> +      </div>
- [ ] great job changing the hamburger to  a button, kindly try to fix the styling of it to match Figma  :

**your button now :** 


![btnf](https://user-images.githubusercontent.com/89282221/185690326-283c3f4e-a9da-4c7e-966e-0b8577a27378.png)

2022-08-19 19:17 UTC, ichala commented on index.html
> +        <a href="#" class="logo-text">Botlhale Setou</a>
- [ ] you did a great job wrapping the logo text inside the `<a>` tag, however that action caused a design issue where the default styles of `<a>` tag have been automatically applied , kindly fix the style of the text to match Figma :

**_- Current Logo design:_** 

![logo](https://user-images.githubusercontent.com/89282221/185691021-44ec30d7-2403-4d9d-9087-418483d3596c.png)

2022-08-19 19:23 UTC, Botlhale-Setou commented on styles.css
> +  background-image: url("top circles.png");
Thanks! Updated url.

2022-08-19 19:29 UTC, Botlhale-Setou commented on index.html
> +      <section class="headline-head">
Converted outer <div to <section and inner <sections to <divs.

2022-08-19 19:42 UTC, Botlhale-Setou commented on index.html
> +        <a href="#" class="logo-text">Botlhale Setou</a>
Removed underlining by setting text-decoration to none.

2022-08-19 19:50 UTC, Botlhale-Setou commented on index.html
> +      </div>
Removed button styling to match Figma template.

2022-08-19 20:11 UTC, Kamba56 approved these changes
Hi @Botlhale-Setou, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- [x] Meaningful commit messages
- [x] All linters checks passed
- [x] Descriptive PR title and description
- [x] Professional Readme
- [ ] Good communication with code reviewers 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 21:18 UTC, Botlhale-Setou commented
Thanks a ton, guys!

2022-08-19 21:19 UTC, merged